Array.from(document.querySelectorAll(".tablefont"))
  .map(tf => tf.innerText.split(/\n/))
  .map(
    ([
      year,
      ,
      name,
      ,
      college,
      ,
      pos,
      ,
      height,
      ,
      weight,
      ,
      handSize,
      ,
      armLength,
      ,
      ,
      fortyYard,
      ,
      benchPress,
      ,
      vertLeap,
      ,
      broadJump,
      ,
      shuttle,
      ,
      threeCone,
      ,
      sixtyYardShuttle
    ]) => ({
      year: year ? year.trim() : "",
      name: name ? name.trim() : "",
      college: college ? college.trim() : "",
      pos: pos ? pos.trim() : "",
      height: height ? height.trim() : "",
      weight: weight ? weight.trim() : "",
      handSize: handSize ? handSize.trim() : "",
      armLength: armLength ? armLength.trim() : "",
      fortyYard: fortyYard ? fortyYard.trim() : "",
      benchPress: benchPress ? benchPress.trim() : "",
      vertLeap: vertLeap ? vertLeap.trim() : "",
      broadJump: broadJump ? broadJump.trim() : "",
      shuttle: shuttle ? shuttle.trim() : "",
      threeCone: threeCone ? threeCone.trim() : "",
      sixtyYardShuttle: sixtyYardShuttle ? sixtyYardShuttle.trim() : ""
    })
  );

//nflcombineresults.com/nflcombinedata_expanded.php

const playerProfiles = [
  {
    year: "2019",
    name: "Johnathan Abram",
    college: "Mississippi State",
    pos: "S",
    height: "71.00",
    weight: "205",
    handSize: "9.63",
    armLength: "31.38",
    fortyYard: "4.45",
    benchPress: "",
    vertLeap: "116",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Paul Adams",
    college: "Missouri",
    pos: "OT",
    height: "78.00",
    weight: "317",
    handSize: "10.00",
    armLength: "33.50",
    fortyYard: "5.18",
    benchPress: "16",
    vertLeap: "27.0",
    broadJump: "103",
    shuttle: "4.74",
    threeCone: "7.68",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Nasir Adderley",
    college: "Delaware",
    pos: "S",
    height: "72.00",
    weight: "206",
    handSize: "9.00",
    armLength: "31.00",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Azeez Al-Shaair",
    college: "Florida Atlantic",
    pos: "LB",
    height: "73.00",
    weight: "234",
    handSize: "9.50",
    armLength: "32.38",
    fortyYard: "16",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Otaro Alaka",
    college: "Texas A&M",
    pos: "LB",
    height: "75.00",
    weight: "239",
    handSize: "9.75",
    armLength: "33.00",
    fortyYard: "4.82",
    benchPress: "20",
    vertLeap: "36.0",
    broadJump: "131",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dakota Allen",
    college: "Texas Tech",
    pos: "LB",
    height: "73.00",
    weight: "232",
    handSize: "9.25",
    armLength: "31.25",
    fortyYard: "4.77",
    benchPress: "23",
    vertLeap: "31.5",
    broadJump: "116",
    shuttle: "4.04",
    threeCone: "6.88",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Josh Allen",
    college: "Kentucky",
    pos: "EDG",
    height: "77.00",
    weight: "262",
    handSize: "8.75",
    armLength: "33.50",
    fortyYard: "4.63",
    benchPress: "28",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Zach Allen",
    college: "Boston College",
    pos: "DE",
    height: "76.00",
    weight: "281",
    handSize: "10.13",
    armLength: "34.75",
    fortyYard: "5.00",
    benchPress: "24",
    vertLeap: "32.0",
    broadJump: "112",
    shuttle: "4.36",
    threeCone: "7.34",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Bryson Allen-Williams",
    college: "South Carolina",
    pos: "LB",
    height: "73.00",
    weight: "236",
    handSize: "9.75",
    armLength: "31.50",
    fortyYard: "4.88",
    benchPress: "14",
    vertLeap: "",
    broadJump: "7.40",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jeff Allison",
    college: "Frenso State (CA)",
    pos: "LB",
    height: "71.00",
    weight: "228",
    handSize: "10.00",
    armLength: "32.25",
    fortyYard: "4.82",
    benchPress: "12",
    vertLeap: "31.0",
    broadJump: "115",
    shuttle: "4.45",
    threeCone: "7.20",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ugo Amadi",
    college: "Oregon",
    pos: "S",
    height: "69.00",
    weight: "199",
    handSize: "9.50",
    armLength: "31.75",
    fortyYard: "4.51",
    benchPress: "18",
    vertLeap: "32.5",
    broadJump: "115",
    shuttle: "4.19",
    threeCone: "7.21",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Rodney Anderson",
    college: "Oklahoma",
    pos: "RB",
    height: "72.00",
    weight: "224",
    handSize: "9.75",
    armLength: "30.75",
    fortyYard: "25",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "J.J. Arcega-Whiteside",
    college: "Stanford",
    pos: "WR",
    height: "74.00",
    weight: "225",
    handSize: "9.50",
    armLength: "33.25",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ryquell Armstead",
    college: "Temple",
    pos: "RB",
    height: "71.00",
    weight: "220",
    handSize: "9.13",
    armLength: "30.63",
    fortyYard: "4.45",
    benchPress: "22",
    vertLeap: "30.0",
    broadJump: "114",
    shuttle: "4.29",
    threeCone: "7.02",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Blessuan Austin",
    college: "Rutgers",
    pos: "CB",
    height: "73.00",
    weight: "198",
    handSize: "10.00",
    armLength: "32.50",
    fortyYard: "15",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jake Bailey",
    college: "Stanford",
    pos: "P",
    height: "73.00",
    weight: "200",
    handSize: "8.75",
    armLength: "30.00",
    fortyYard: "4.72",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Zack Bailey",
    college: "South Carolina",
    pos: "OL",
    height: "77.00",
    weight: "299",
    handSize: "9.63",
    armLength: "33.00",
    fortyYard: "24",
    benchPress: "28.0",
    vertLeap: "103",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Derrick Baity",
    college: "Kentucky",
    pos: "CB",
    height: "74.00",
    weight: "197",
    handSize: "8.63",
    armLength: "31.50",
    fortyYard: "10",
    benchPress: "38.5",
    vertLeap: "127",
    broadJump: "4.31",
    shuttle: "7.06",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Deandre Baker",
    college: "Georgia",
    pos: "CB",
    height: "71.00",
    weight: "193",
    handSize: "9.00",
    armLength: "32.00",
    fortyYard: "4.52",
    benchPress: "14",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Corey Ballentine",
    college: "Washburn (KS)",
    pos: "CB",
    height: "71.00",
    weight: "196",
    handSize: "9.50",
    armLength: "31.63",
    fortyYard: "4.47",
    benchPress: "15",
    vertLeap: "39.5",
    broadJump: "135",
    shuttle: "4.14",
    threeCone: "6.82",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ben Banogu",
    college: "Texas Christian",
    pos: "EDG",
    height: "75.00",
    weight: "250",
    handSize: "9.00",
    armLength: "33.63",
    fortyYard: "4.62",
    benchPress: "23",
    vertLeap: "40.0",
    broadJump: "134",
    shuttle: "4.27",
    threeCone: "7.02",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Alex Barnes",
    college: "Kansas State",
    pos: "RB",
    height: "72.00",
    weight: "226",
    handSize: "10.00",
    armLength: "31.00",
    fortyYard: "4.59",
    benchPress: "34",
    vertLeap: "38.5",
    broadJump: "126",
    shuttle: "4.10",
    threeCone: "6.95",
    sixtyYardShuttle: "11.72"
  },
  {
    year: "2019",
    name: "Alex Bars",
    college: "Notre Dame",
    pos: "OG",
    height: "78.00",
    weight: "312",
    handSize: "9.38",
    armLength: "32.75",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Cody Barton",
    college: "Utah",
    pos: "LB",
    height: "74.00",
    weight: "237",
    handSize: "9.25",
    armLength: "31.88",
    fortyYard: "4.64",
    benchPress: "30",
    vertLeap: "32.5",
    broadJump: "116",
    shuttle: "4.03",
    threeCone: "6.90",
    sixtyYardShuttle: "11.47"
  },
  {
    year: "2019",
    name: "Jackson Barton",
    college: "Utah",
    pos: "OT",
    height: "79.00",
    weight: "310",
    handSize: "9.25",
    armLength: "34.00",
    fortyYard: "5.18",
    benchPress: "25",
    vertLeap: "27.0",
    broadJump: "109",
    shuttle: "4.66",
    threeCone: "7.85",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ryan Bates",
    college: "Penn State",
    pos: "OT",
    height: "76.00",
    weight: "306",
    handSize: "9.50",
    armLength: "32.50",
    fortyYard: "5.09",
    benchPress: "28",
    vertLeap: "27.0",
    broadJump: "102",
    shuttle: "4.53",
    threeCone: "7.45",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "John Battle",
    college: "Louisiana State",
    pos: "S",
    height: "72.00",
    weight: "201",
    handSize: "9.63",
    armLength: "31.75",
    fortyYard: "4.67",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Terry Beckner",
    college: "Missouri",
    pos: "DT",
    height: "76.00",
    weight: "296",
    handSize: "8.63",
    armLength: "32.25",
    fortyYard: "5.19",
    benchPress: "28",
    vertLeap: "24.5",
    broadJump: "98",
    shuttle: "4.82",
    threeCone: "7.97",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mike Bell",
    college: "Frenso State (CA)",
    pos: "S",
    height: "75.00",
    weight: "210",
    handSize: "9.25",
    armLength: "32.38",
    fortyYard: "4.83",
    benchPress: "10",
    vertLeap: "30.0",
    broadJump: "118",
    shuttle: "4.46",
    threeCone: "7.10",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Beau Benzschawel",
    college: "Wisconsin",
    pos: "OG",
    height: "78.00",
    weight: "309",
    handSize: "9.63",
    armLength: "33.38",
    fortyYard: "5.24",
    benchPress: "20",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Marquise Blair",
    college: "Utah",
    pos: "S",
    height: "73.00",
    weight: "195",
    handSize: "8.25",
    armLength: "30.75",
    fortyYard: "4.48",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kendall Blanton",
    college: "Missouri",
    pos: "TE",
    height: "78.00",
    weight: "262",
    handSize: "10.38",
    armLength: "33.75",
    fortyYard: "4.95",
    benchPress: "22",
    vertLeap: "31.0",
    broadJump: "113",
    shuttle: "4.42",
    threeCone: "7.37",
    sixtyYardShuttle: "12.28"
  },
  {
    year: "2019",
    name: "Nick Bosa",
    college: "Ohio State",
    pos: "DE",
    height: "76.00",
    weight: "266",
    handSize: "10.75",
    armLength: "33.00",
    fortyYard: "4.79",
    benchPress: "29",
    vertLeap: "33.5",
    broadJump: "116",
    shuttle: "4.14",
    threeCone: "7.10",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kris Boyd",
    college: "Texas",
    pos: "CB",
    height: "71.00",
    weight: "201",
    handSize: "9.00",
    armLength: "30.75",
    fortyYard: "4.45",
    benchPress: "19",
    vertLeap: "36.5",
    broadJump: "127",
    shuttle: "4.08",
    threeCone: "6.94",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Miles Boykin",
    college: "Notre Dame",
    pos: "WR",
    height: "76.00",
    weight: "220",
    handSize: "9.88",
    armLength: "33.50",
    fortyYard: "4.42",
    benchPress: "12",
    vertLeap: "43.5",
    broadJump: "140",
    shuttle: "4.07",
    threeCone: "6.77",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Garrett Bradbury",
    college: "North Carolina State",
    pos: "C",
    height: "75.00",
    weight: "306",
    handSize: "10.50",
    armLength: "31.75",
    fortyYard: "4.92",
    benchPress: "34",
    vertLeap: "31.0",
    broadJump: "104",
    shuttle: "4.53",
    threeCone: "7.41",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Tyre Brady",
    college: "Marshall (WV)",
    pos: "WR",
    height: "75.00",
    weight: "211",
    handSize: "9.75",
    armLength: "33.63",
    fortyYard: "12",
    benchPress: "32.0",
    vertLeap: "117",
    broadJump: "4.25",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jordan Brailford",
    college: "Oklahoma State",
    pos: "EDG",
    height: "75.00",
    weight: "252",
    handSize: "9.13",
    armLength: "32.50",
    fortyYard: "4.65",
    benchPress: "22",
    vertLeap: "37.5",
    broadJump: "126",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Nick Brossette",
    college: "Louisiana State",
    pos: "RB",
    height: "71.00",
    weight: "209",
    handSize: "8.63",
    armLength: "30.00",
    fortyYard: "4.72",
    benchPress: "15",
    vertLeap: "35.5",
    broadJump: "118",
    shuttle: "4.44",
    threeCone: "7.38",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "A.J. Brown",
    college: "Mississippi",
    pos: "WR",
    height: "72.00",
    weight: "226",
    handSize: "9.75",
    armLength: "32.88",
    fortyYard: "4.49",
    benchPress: "19",
    vertLeap: "36.5",
    broadJump: "120",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Blace Brown",
    college: "Troy (AL)",
    pos: "CB",
    height: "72.00",
    weight: "194",
    handSize: "9.75",
    armLength: "32.00",
    fortyYard: "4.75",
    benchPress: "14",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jordan Brown",
    college: "South Dakota State",
    pos: "CB",
    height: "72.00",
    weight: "201",
    handSize: "9.63",
    armLength: "30.50",
    fortyYard: "4.51",
    benchPress: "13",
    vertLeap: "39.5",
    broadJump: "128",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Keenen Brown",
    college: "Texas State",
    pos: "TE",
    height: "74.00",
    weight: "250",
    handSize: "9.88",
    armLength: "34.50",
    fortyYard: "4.75",
    benchPress: "17",
    vertLeap: "33.0",
    broadJump: "117",
    shuttle: "4.51",
    threeCone: "7.27",
    sixtyYardShuttle: "12.25"
  },
  {
    year: "2019",
    name: "Marquise Brown",
    college: "Oklahoma",
    pos: "WR",
    height: "69.00",
    weight: "166",
    handSize: "9.00",
    armLength: "30.50",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jake Browning",
    college: "Washington",
    pos: "QB",
    height: "74.00",
    weight: "211",
    handSize: "9.00",
    armLength: "32.50",
    fortyYard: "4.74",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Austin Bryant",
    college: "Clemson",
    pos: "DE",
    height: "76.00",
    weight: "271",
    handSize: "9.63",
    armLength: "34.63",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Isaiah Buggs",
    college: "Alabama",
    pos: "DT",
    height: "75.00",
    weight: "306",
    handSize: "9.25",
    armLength: "31.25",
    fortyYard: "5.15",
    benchPress: "20",
    vertLeap: "24.5",
    broadJump: "96",
    shuttle: "4.83",
    threeCone: "8.01",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Sean Bunting",
    college: "Central Michigan",
    pos: "CB",
    height: "72.00",
    weight: "195",
    handSize: "9.63",
    armLength: "31.75",
    fortyYard: "4.42",
    benchPress: "14",
    vertLeap: "41.5",
    broadJump: "126",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Brian Burns",
    college: "Florida State",
    pos: "EDG",
    height: "77.00",
    weight: "249",
    handSize: "10.00",
    armLength: "33.88",
    fortyYard: "4.53",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ben Burr-Kirven",
    college: "Washington",
    pos: "LB",
    height: "72.00",
    weight: "230",
    handSize: "8.88",
    armLength: "31.88",
    fortyYard: "4.56",
    benchPress: "21",
    vertLeap: "34.5",
    broadJump: "121",
    shuttle: "4.09",
    threeCone: "6.85",
    sixtyYardShuttle: "11.43"
  },
  {
    year: "2019",
    name: "Devin Bush",
    college: "Michigan",
    pos: "LB",
    height: "71.00",
    weight: "234",
    handSize: "9.63",
    armLength: "32.00",
    fortyYard: "4.43",
    benchPress: "21",
    vertLeap: "40.5",
    broadJump: "124",
    shuttle: "4.23",
    threeCone: "6.93",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Emmanuel Butler",
    college: "Northern Arizona",
    pos: "WR",
    height: "75.00",
    weight: "217",
    handSize: "10.13",
    armLength: "33.00",
    fortyYard: "11",
    benchPress: "36.0",
    vertLeap: "115",
    broadJump: "4.22",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Hakeem Butler",
    college: "Iowa State",
    pos: "WR",
    height: "77.00",
    weight: "227",
    handSize: "10.75",
    armLength: "35.25",
    fortyYard: "4.48",
    benchPress: "18",
    vertLeap: "36.0",
    broadJump: "128",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Yodny Cajuste",
    college: "West Virginia",
    pos: "OT",
    height: "77.00",
    weight: "312",
    handSize: "10.00",
    armLength: "34.00",
    fortyYard: "32",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Shaq Calhoun",
    college: "Mississippi State",
    pos: "OG",
    height: "74.00",
    weight: "310",
    handSize: "10.00",
    armLength: "33.13",
    fortyYard: "5.07",
    benchPress: "26",
    vertLeap: "28.5",
    broadJump: "105",
    shuttle: "4.62",
    threeCone: "7.46",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Parris Campbell",
    college: "Ohio State",
    pos: "WR",
    height: "72.00",
    weight: "205",
    handSize: "9.50",
    armLength: "32.25",
    fortyYard: "4.31",
    benchPress: "11",
    vertLeap: "40.0",
    broadJump: "135",
    shuttle: "4.03",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Malik Carney",
    college: "North Carolina",
    pos: "EDG",
    height: "74.00",
    weight: "251",
    handSize: "9.88",
    armLength: "33.38",
    fortyYard: "4.73",
    benchPress: "25",
    vertLeap: "33.0",
    broadJump: "113",
    shuttle: "7.40",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Blake Cashman",
    college: "Minnesota",
    pos: "LB",
    height: "73.00",
    weight: "237",
    handSize: "8.75",
    armLength: "30.13",
    fortyYard: "4.50",
    benchPress: "18",
    vertLeap: "37.5",
    broadJump: "124",
    shuttle: "4.12",
    threeCone: "6.95",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Hamp Cheevers",
    college: "Boston College",
    pos: "CB",
    height: "69.00",
    weight: "169",
    handSize: "8.63",
    armLength: "30.50",
    fortyYard: "4.52",
    benchPress: "8",
    vertLeap: "39.0",
    broadJump: "122",
    shuttle: "4.25",
    threeCone: "6.96",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Demarcus Christmas",
    college: "Florida State",
    pos: "DT",
    height: "75.00",
    weight: "294",
    handSize: "9.13",
    armLength: "32.75",
    fortyYard: "5.08",
    benchPress: "22",
    vertLeap: "25.5",
    broadJump: "101",
    shuttle: "5.07",
    threeCone: "8.13",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "L.J. Collier",
    college: "Texas Christian",
    pos: "DE",
    height: "74.00",
    weight: "283",
    handSize: "10.00",
    armLength: "34.00",
    fortyYard: "4.91",
    benchPress: "25",
    vertLeap: "30.0",
    broadJump: "118",
    shuttle: "4.78",
    threeCone: "7.71",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "John Cominsky",
    college: "Charleston (WV)",
    pos: "DE",
    height: "77.00",
    weight: "286",
    handSize: "9.75",
    armLength: "33.50",
    fortyYard: "4.69",
    benchPress: "22",
    vertLeap: "33.5",
    broadJump: "116",
    shuttle: "4.38",
    threeCone: "7.03",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Te'Von Coney",
    college: "Notre Dame",
    pos: "LB",
    height: "73.00",
    weight: "234",
    handSize: "9.50",
    armLength: "32.88",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ryan Connelly",
    college: "Wisconsin",
    pos: "LB",
    height: "74.00",
    weight: "242",
    handSize: "9.38",
    armLength: "30.88",
    fortyYard: "4.66",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "C.J. Conrad",
    college: "Kentucky",
    pos: "TE",
    height: "76.00",
    weight: "249",
    handSize: "9.25",
    armLength: "31.00",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Byron Cowart",
    college: "Maryland",
    pos: "DT",
    height: "75.00",
    weight: "298",
    handSize: "10.00",
    armLength: "33.75",
    fortyYard: "5.16",
    benchPress: "26",
    vertLeap: "30.0",
    broadJump: "111",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jonathan Crawford",
    college: "Indiana",
    pos: "S",
    height: "73.00",
    weight: "205",
    handSize: "9.25",
    armLength: "31.50",
    fortyYard: "16",
    benchPress: "31.5",
    vertLeap: "115",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Xavier Crawford",
    college: "Central Michigan",
    pos: "CB",
    height: "71.00",
    weight: "187",
    handSize: "9.00",
    armLength: "29.13",
    fortyYard: "4.48",
    benchPress: "11",
    vertLeap: "37.5",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Maxx Crosby",
    college: "Eastern Michigan",
    pos: "EDG",
    height: "77.00",
    weight: "255",
    handSize: "9.75",
    armLength: "32.88",
    fortyYard: "4.66",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jamal Custis",
    college: "Syracuse",
    pos: "WR",
    height: "76.00",
    weight: "214",
    handSize: "10.88",
    armLength: "33.88",
    fortyYard: "4.50",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dennis Daley",
    college: "South Carolina",
    pos: "OT",
    height: "77.00",
    weight: "317",
    handSize: "9.50",
    armLength: "33.38",
    fortyYard: "5.23",
    benchPress: "20",
    vertLeap: "26.5",
    broadJump: "103",
    shuttle: "4.92",
    threeCone: "7.95",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Davante Davis",
    college: "Texas",
    pos: "CB",
    height: "74.00",
    weight: "202",
    handSize: "9.75",
    armLength: "31.38",
    fortyYard: "4.57",
    benchPress: "14",
    vertLeap: "37.0",
    broadJump: "125",
    shuttle: "4.15",
    threeCone: "6.76",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Deshaun Davis",
    college: "Auburn",
    pos: "LB",
    height: "71.00",
    weight: "234",
    handSize: "10.00",
    armLength: "31.25",
    fortyYard: "25",
    benchPress: "31.0",
    vertLeap: "111",
    broadJump: "4.38",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Felton Davis",
    college: "Michigan State",
    pos: "WR",
    height: "75.00",
    weight: "211",
    handSize: "10.25",
    armLength: "32.75",
    fortyYard: "21",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jamal Davis",
    college: "Akron",
    pos: "EDG",
    height: "75.00",
    weight: "243",
    handSize: "10.25",
    armLength: "34.25",
    fortyYard: "4.60",
    benchPress: "19",
    vertLeap: "39.0",
    broadJump: "122",
    shuttle: "4.44",
    threeCone: "7.00",
    sixtyYardShuttle: "11.78"
  },
  {
    year: "2019",
    name: "Nate Davis",
    college: "North Carolina Charlotte",
    pos: "OG",
    height: "75.00",
    weight: "316",
    handSize: "9.50",
    armLength: "33.13",
    fortyYard: "5.23",
    benchPress: "23",
    vertLeap: "26.0",
    broadJump: "107",
    shuttle: "4.83",
    threeCone: "7.94",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ryan Davis",
    college: "Auburn",
    pos: "WR",
    height: "70.00",
    weight: "189",
    handSize: "9.25",
    armLength: "30.88",
    fortyYard: "12",
    benchPress: "35.0",
    vertLeap: "124",
    broadJump: "4.23",
    shuttle: "7.09",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jamel Dean",
    college: "Auburn",
    pos: "CB",
    height: "73.00",
    weight: "206",
    handSize: "9.13",
    armLength: "31.75",
    fortyYard: "4.30",
    benchPress: "16",
    vertLeap: "41.0",
    broadJump: "130",
    shuttle: "4.19",
    threeCone: "7.02",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Michael Deiter",
    college: "Wisconsin",
    pos: "OG",
    height: "77.00",
    weight: "309",
    handSize: "10.75",
    armLength: "33.13",
    fortyYard: "5.23",
    benchPress: "21",
    vertLeap: "28.0",
    broadJump: "105",
    shuttle: "4.81",
    threeCone: "7.88",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Lukas Denis",
    college: "Boston College",
    pos: "S",
    height: "71.00",
    weight: "190",
    handSize: "9.50",
    armLength: "31.25",
    fortyYard: "4.64",
    benchPress: "16",
    vertLeap: "33.5",
    broadJump: "116",
    shuttle: "4.09",
    threeCone: "6.89",
    sixtyYardShuttle: "11.42"
  },
  {
    year: "2019",
    name: "Andre Dillard",
    college: "Washington State",
    pos: "OT",
    height: "77.00",
    weight: "315",
    handSize: "10.00",
    armLength: "33.50",
    fortyYard: "4.96",
    benchPress: "24",
    vertLeap: "29.0",
    broadJump: "118",
    shuttle: "4.40",
    threeCone: "7.44",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "D'Cota Dixon",
    college: "Wisconsin",
    pos: "S",
    height: "70.00",
    weight: "204",
    handSize: "9.13",
    armLength: "29.25",
    fortyYard: "4.81",
    benchPress: "20",
    vertLeap: "33.5",
    broadJump: "119",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Johnnie Dixon",
    college: "Ohio State",
    pos: "WR",
    height: "70.00",
    weight: "201",
    handSize: "9.63",
    armLength: "30.25",
    fortyYard: "4.41",
    benchPress: "16",
    vertLeap: "37.5",
    broadJump: "120",
    shuttle: "4.43",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Tyrel Dodson",
    college: "Texas A&M",
    pos: "LB",
    height: "72.00",
    weight: "237",
    handSize: "9.13",
    armLength: "31.75",
    fortyYard: "4.60",
    benchPress: "24",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Greg Dortch",
    college: "Wake Forest",
    pos: "WR",
    height: "67.00",
    weight: "173",
    handSize: "9.25",
    armLength: "29.25",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Keelan Doss",
    college: "UC-Davis",
    pos: "WR",
    height: "74.00",
    weight: "211",
    handSize: "9.50",
    armLength: "31.75",
    fortyYard: "8",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ashton Dulin",
    college: "Malone (OH)",
    pos: "WR",
    height: "73.00",
    weight: "215",
    handSize: "9.00",
    armLength: "33.38",
    fortyYard: "4.43",
    benchPress: "13",
    vertLeap: "38.0",
    broadJump: "121",
    shuttle: "4.22",
    threeCone: "7.00",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jovon Durante",
    college: "Florida Atlantic",
    pos: "WR",
    height: "71.00",
    weight: "160",
    handSize: "8.75",
    armLength: "31.13",
    fortyYard: "4.55",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Chuma Edoga",
    college: "Southern California",
    pos: "OT",
    height: "75.00",
    weight: "308",
    handSize: "9.63",
    armLength: "34.75",
    fortyYard: "5.19",
    benchPress: "21",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "David Edwards",
    college: "Wisconsin",
    pos: "OT",
    height: "78.00",
    weight: "308",
    handSize: "9.75",
    armLength: "33.38",
    fortyYard: "5.28",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mike Edwards",
    college: "Kentucky",
    pos: "S",
    height: "70.00",
    weight: "205",
    handSize: "9.38",
    armLength: "30.88",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "T.J. Edwards",
    college: "Wisconsin",
    pos: "LB",
    height: "72.00",
    weight: "230",
    handSize: "9.38",
    armLength: "31.25",
    fortyYard: "16",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Emeke Egbule",
    college: "Houston",
    pos: "LB",
    height: "74.00",
    weight: "245",
    handSize: "9.25",
    armLength: "33.00",
    fortyYard: "4.65",
    benchPress: "20",
    vertLeap: "33.0",
    broadJump: "119",
    shuttle: "4.38",
    threeCone: "7.38",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Noah Fant",
    college: "Iowa",
    pos: "TE",
    height: "76.00",
    weight: "249",
    handSize: "9.75",
    armLength: "33.50",
    fortyYard: "4.50",
    benchPress: "20",
    vertLeap: "39.5",
    broadJump: "127",
    shuttle: "4.22",
    threeCone: "6.81",
    sixtyYardShuttle: "11.49"
  },
  {
    year: "2019",
    name: "Rashad Fenton",
    college: "South Carolina",
    pos: "CB",
    height: "71.00",
    weight: "193",
    handSize: "8.75",
    armLength: "30.38",
    fortyYard: "4.52",
    benchPress: "12",
    vertLeap: "34.0",
    broadJump: "117",
    shuttle: "4.25",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jazz Ferguson",
    college: "Northwestern State (LA)",
    pos: "WR",
    height: "77.00",
    weight: "227",
    handSize: "9.25",
    armLength: "34.25",
    fortyYard: "4.45",
    benchPress: "8",
    vertLeap: "37.0",
    broadJump: "123",
    shuttle: "4.59",
    threeCone: "7.25",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Clelin Ferrell",
    college: "Clemson",
    pos: "DE",
    height: "76.00",
    weight: "264",
    handSize: "10.50",
    armLength: "34.13",
    fortyYard: "25",
    benchPress: "",
    vertLeap: "4.40",
    broadJump: "7.26",
    shuttle: "12.07",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mark Fields",
    college: "Clemson",
    pos: "CB",
    height: "70.00",
    weight: "192",
    handSize: "9.13",
    armLength: "30.50",
    fortyYard: "4.37",
    benchPress: "18",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ryan Finley",
    college: "North Carolina State",
    pos: "QB",
    height: "76.00",
    weight: "213",
    handSize: "9.50",
    armLength: "32.88",
    fortyYard: "4.73",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Nick Fitzgerald",
    college: "Mississippi State",
    pos: "QB",
    height: "77.00",
    weight: "226",
    handSize: "9.75",
    armLength: "31.88",
    fortyYard: "4.64",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jack Fox",
    college: "Rice (TX)",
    pos: "P",
    height: "74.00",
    weight: "213",
    handSize: "9.25",
    armLength: "31.75",
    fortyYard: "4.73",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Hjalte Froholdt",
    college: "Arkansas",
    pos: "OG",
    height: "77.00",
    weight: "306",
    handSize: "9.75",
    armLength: "31.25",
    fortyYard: "5.20",
    benchPress: "31",
    vertLeap: "27.5",
    broadJump: "105",
    shuttle: "4.54",
    threeCone: "7.51",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Travis Fulgham",
    college: "Old Dominion (VA)",
    pos: "WR",
    height: "74.00",
    weight: "215",
    handSize: "9.50",
    armLength: "33.75",
    fortyYard: "4.58",
    benchPress: "15",
    vertLeap: "36.5",
    broadJump: "126",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Lamont Gaillard",
    college: "Georgia",
    pos: "C",
    height: "75.00",
    weight: "305",
    handSize: "10.38",
    armLength: "33.50",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Greg Gaines",
    college: "Washington",
    pos: "DT",
    height: "73.00",
    weight: "312",
    handSize: "9.63",
    armLength: "31.25",
    fortyYard: "5.16",
    benchPress: "30",
    vertLeap: "31.0",
    broadJump: "109",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Malik Gant",
    college: "Marshall (WV)",
    pos: "S",
    height: "72.00",
    weight: "209",
    handSize: "8.88",
    armLength: "30.50",
    fortyYard: "4.63",
    benchPress: "17",
    vertLeap: "34.5",
    broadJump: "114",
    shuttle: "4.30",
    threeCone: "7.45",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Chauncey Gardner-Johnson",
    college: "Florida",
    pos: "S",
    height: "71.00",
    weight: "210",
    handSize: "9.25",
    armLength: "30.88",
    fortyYard: "4.48",
    benchPress: "17",
    vertLeap: "36.0",
    broadJump: "117",
    shuttle: "4.20",
    threeCone: "7.03",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Rashan Gary",
    college: "Michigan",
    pos: "DE",
    height: "76.00",
    weight: "277",
    handSize: "9.63",
    armLength: "34.13",
    fortyYard: "4.58",
    benchPress: "26",
    vertLeap: "38.0",
    broadJump: "120",
    shuttle: "4.29",
    threeCone: "7.26",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Myles Gaskin",
    college: "Washington",
    pos: "RB",
    height: "69.00",
    weight: "205",
    handSize: "8.75",
    armLength: "29.50",
    fortyYard: "4.58",
    benchPress: "24",
    vertLeap: "35.5",
    broadJump: "118",
    shuttle: "4.27",
    threeCone: "7.19",
    sixtyYardShuttle: "11.77"
  },
  {
    year: "2019",
    name: "Matt Gay",
    college: "Utah",
    pos: "K",
    height: "72.00",
    weight: "232",
    handSize: "9.00",
    armLength: "30.50",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Zach Gentry",
    college: "Michigan",
    pos: "TE",
    height: "80.00",
    weight: "265",
    handSize: "9.50",
    armLength: "34.13",
    fortyYard: "4.90",
    benchPress: "12",
    vertLeap: "29.5",
    broadJump: "110",
    shuttle: "4.53",
    threeCone: "7.40",
    sixtyYardShuttle: "12.43"
  },
  {
    year: "2019",
    name: "Joe Giles-Harris",
    college: "Duke",
    pos: "LB",
    height: "74.00",
    weight: "234",
    handSize: "8.50",
    armLength: "31.25",
    fortyYard: "4.75",
    benchPress: "17",
    vertLeap: "29.5",
    broadJump: "111",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kevin Givens",
    college: "Penn State",
    pos: "DT",
    height: "73.00",
    weight: "285",
    handSize: "9.63",
    armLength: "32.13",
    fortyYard: "5.08",
    benchPress: "32",
    vertLeap: "31.0",
    broadJump: "115",
    shuttle: "4.62",
    threeCone: "7.63",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dan Godsil",
    college: "Indiana",
    pos: "LS",
    height: "76.00",
    weight: "241",
    handSize: "10.13",
    armLength: "33.00",
    fortyYard: "5.00",
    benchPress: "16",
    vertLeap: "34.5",
    broadJump: "118",
    shuttle: "4.55",
    threeCone: "7.56",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Terry Godwin",
    college: "Georgia",
    pos: "WR",
    height: "71.00",
    weight: "184",
    handSize: "9.38",
    armLength: "30.00",
    fortyYard: "4.55",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Carl Granderson",
    college: "Wyoming",
    pos: "EDG",
    height: "77.00",
    weight: "254",
    handSize: "9.63",
    armLength: "34.00",
    fortyYard: "4.79",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Gerri Green",
    college: "Mississippi State",
    pos: "EDG",
    height: "76.00",
    weight: "252",
    handSize: "10.00",
    armLength: "33.00",
    fortyYard: "4.63",
    benchPress: "24",
    vertLeap: "35.0",
    broadJump: "114",
    shuttle: "4.42",
    threeCone: "7.27",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ethan Greenidge",
    college: "Villanova",
    pos: "OL",
    height: "76.00",
    weight: "327",
    handSize: "10.38",
    armLength: "34.75",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dre Greenlaw",
    college: "Arkansas",
    pos: "LB",
    height: "71.00",
    weight: "237",
    handSize: "9.88",
    armLength: "32.25",
    fortyYard: "24",
    benchPress: "33.0",
    vertLeap: "117",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Will Grier",
    college: "West Virginia",
    pos: "QB",
    height: "74.00",
    weight: "217",
    handSize: "9.38",
    armLength: "31.50",
    fortyYard: "4.84",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Porter Gustin",
    college: "Southern California",
    pos: "EDG",
    height: "76.00",
    weight: "255",
    handSize: "10.00",
    armLength: "33.00",
    fortyYard: "4.69",
    benchPress: "31",
    vertLeap: "35.5",
    broadJump: "119",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Emanuel Hall",
    college: "Missouri",
    pos: "WR",
    height: "74.00",
    weight: "201",
    handSize: "9.75",
    armLength: "33.25",
    fortyYard: "4.39",
    benchPress: "15",
    vertLeap: "43.5",
    broadJump: "141",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Nate Hall",
    college: "Northwestern",
    pos: "LB",
    height: "74.00",
    weight: "225",
    handSize: "9.38",
    armLength: "32.25",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Terez Hall",
    college: "Missouri",
    pos: "LB",
    height: "73.00",
    weight: "230",
    handSize: "10.38",
    armLength: "33.50",
    fortyYard: "20",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Saquan Hampton",
    college: "Rutgers",
    pos: "S",
    height: "73.00",
    weight: "206",
    handSize: "8.63",
    armLength: "31.63",
    fortyYard: "4.48",
    benchPress: "14",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Terrill Hanks",
    college: "New Mexico State",
    pos: "LB",
    height: "74.00",
    weight: "242",
    handSize: "9.75",
    armLength: "33.50",
    fortyYard: "4.98",
    benchPress: "21",
    vertLeap: "35.5",
    broadJump: "118",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Chase Hansen",
    college: "Utah",
    pos: "LB",
    height: "75.00",
    weight: "222",
    handSize: "9.38",
    armLength: "30.50",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mecole Hardman",
    college: "Georgia",
    pos: "WR",
    height: "70.00",
    weight: "187",
    handSize: "9.00",
    armLength: "30.25",
    fortyYard: "4.33",
    benchPress: "17",
    vertLeap: "36.5",
    broadJump: "119",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kelvin Harmon",
    college: "North Carolina State",
    pos: "WR",
    height: "74.00",
    weight: "221",
    handSize: "9.50",
    armLength: "32.50",
    fortyYard: "4.60",
    benchPress: "18",
    vertLeap: "32.5",
    broadJump: "117",
    shuttle: "4.32",
    threeCone: "7.15",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Damien Harris",
    college: "Alabama",
    pos: "RB",
    height: "70.00",
    weight: "216",
    handSize: "9.75",
    armLength: "30.75",
    fortyYard: "4.57",
    benchPress: "16",
    vertLeap: "37.0",
    broadJump: "121",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Will Harris",
    college: "Boston College",
    pos: "S",
    height: "73.00",
    weight: "207",
    handSize: "9.00",
    armLength: "31.25",
    fortyYard: "4.41",
    benchPress: "20",
    vertLeap: "36.5",
    broadJump: "123",
    shuttle: "4.12",
    threeCone: "6.91",
    sixtyYardShuttle: "11.42"
  },
  {
    year: "2019",
    name: "N'Keal Harry",
    college: "Arizona State",
    pos: "WR",
    height: "74.00",
    weight: "228",
    handSize: "9.50",
    armLength: "33.00",
    fortyYard: "4.53",
    benchPress: "27",
    vertLeap: "38.5",
    broadJump: "122",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Montre Hartage",
    college: "Northwestern",
    pos: "CB",
    height: "71.00",
    weight: "190",
    handSize: "9.00",
    armLength: "31.75",
    fortyYard: "4.68",
    benchPress: "9",
    vertLeap: "34.5",
    broadJump: "123",
    shuttle: "4.08",
    threeCone: "6.95",
    sixtyYardShuttle: "11.50"
  },
  {
    year: "2019",
    name: "Dwayne Haskins",
    college: "Ohio State",
    pos: "QB",
    height: "75.00",
    weight: "231",
    handSize: "9.63",
    armLength: "33.50",
    fortyYard: "5.04",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Phil Haynes",
    college: "Wake Forest",
    pos: "OG",
    height: "76.00",
    weight: "322",
    handSize: "9.50",
    armLength: "33.50",
    fortyYard: "5.20",
    benchPress: "33",
    vertLeap: "31.0",
    broadJump: "108",
    shuttle: "4.95",
    threeCone: "7.76",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Daniel Helm",
    college: "Duke",
    pos: "TE",
    height: "76.00",
    weight: "249",
    handSize: "9.50",
    armLength: "33.38",
    fortyYard: "4.89",
    benchPress: "14",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Darrell Henderson",
    college: "Memphis",
    pos: "RB",
    height: "68.00",
    weight: "208",
    handSize: "8.63",
    armLength: "31.00",
    fortyYard: "4.49",
    benchPress: "22",
    vertLeap: "33.5",
    broadJump: "121",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Nate Herbig",
    college: "Stanford",
    pos: "OG",
    height: "75.00",
    weight: "335",
    handSize: "10.13",
    armLength: "33.25",
    fortyYard: "5.41",
    benchPress: "29",
    vertLeap: "24.0",
    broadJump: "90",
    shuttle: "5.04",
    threeCone: "8.15",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Karan Higdon",
    college: "Michigan",
    pos: "RB",
    height: "69.00",
    weight: "206",
    handSize: "9.63",
    armLength: "30.75",
    fortyYard: "4.49",
    benchPress: "21",
    vertLeap: "34.0",
    broadJump: "123",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Justice Hill",
    college: "Oklahoma State",
    pos: "RB",
    height: "70.00",
    weight: "198",
    handSize: "9.50",
    armLength: "31.63",
    fortyYard: "4.40",
    benchPress: "21",
    vertLeap: "40.0",
    broadJump: "130",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Trysten Hill",
    college: "Central Florida",
    pos: "DT",
    height: "75.00",
    weight: "308",
    handSize: "10.25",
    armLength: "33.38",
    fortyYard: "5.04",
    benchPress: "28",
    vertLeap: "35.0",
    broadJump: "115",
    shuttle: "4.38",
    threeCone: "7.70",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "T.J. Hockenson",
    college: "Iowa",
    pos: "TE",
    height: "77.00",
    weight: "251",
    handSize: "9.50",
    armLength: "32.25",
    fortyYard: "4.70",
    benchPress: "17",
    vertLeap: "37.5",
    broadJump: "123",
    shuttle: "4.18",
    threeCone: "7.02",
    sixtyYardShuttle: "11.55"
  },
  {
    year: "2019",
    name: "Alijah Holder",
    college: "Stanford",
    pos: "CB",
    height: "73.00",
    weight: "191",
    handSize: "9.50",
    armLength: "32.50",
    fortyYard: "4.60",
    benchPress: "9",
    vertLeap: "36.0",
    broadJump: "121",
    shuttle: "4.15",
    threeCone: "6.70",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Justin Hollins",
    college: "Oregon",
    pos: "EDG",
    height: "77.00",
    weight: "248",
    handSize: "10.38",
    armLength: "33.38",
    fortyYard: "4.50",
    benchPress: "25",
    vertLeap: "36.5",
    broadJump: "119",
    shuttle: "4.40",
    threeCone: "7.06",
    sixtyYardShuttle: "11.94"
  },
  {
    year: "2019",
    name: "Elijah Holyfield",
    college: "Georgia",
    pos: "RB",
    height: "70.00",
    weight: "217",
    handSize: "9.00",
    armLength: "30.38",
    fortyYard: "4.78",
    benchPress: "26",
    vertLeap: "29.5",
    broadJump: "118",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Travis Homer",
    college: "Miami (FL)",
    pos: "RB",
    height: "70.00",
    weight: "201",
    handSize: "10.00",
    armLength: "31.50",
    fortyYard: "4.48",
    benchPress: "17",
    vertLeap: "39.5",
    broadJump: "130",
    shuttle: "4.31",
    threeCone: "7.07",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Amani Hooker",
    college: "Iowa",
    pos: "S",
    height: "71.00",
    weight: "210",
    handSize: "9.13",
    armLength: "30.13",
    fortyYard: "4.48",
    benchPress: "14",
    vertLeap: "37.0",
    broadJump: "123",
    shuttle: "4.10",
    threeCone: "6.81",
    sixtyYardShuttle: "11.59"
  },
  {
    year: "2019",
    name: "Albert Huggins",
    college: "Clemson",
    pos: "DT",
    height: "75.00",
    weight: "305",
    handSize: "10.63",
    armLength: "33.50",
    fortyYard: "5.12",
    benchPress: "35",
    vertLeap: "25.5",
    broadJump: "101",
    shuttle: "4.84",
    threeCone: "7.84",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Lil'Jordan Humphrey",
    college: "Texas",
    pos: "WR",
    height: "76.00",
    weight: "210",
    handSize: "9.50",
    armLength: "32.75",
    fortyYard: "4.75",
    benchPress: "13",
    vertLeap: "33.5",
    broadJump: "119",
    shuttle: "4.29",
    threeCone: "7.09",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jalen Hurd",
    college: "Baylor",
    pos: "WR",
    height: "77.00",
    weight: "226",
    handSize: "10.25",
    armLength: "32.00",
    fortyYard: "23",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Alec Ingold",
    college: "Wisconsin",
    pos: "FB",
    height: "73.00",
    weight: "242",
    handSize: "9.63",
    armLength: "31.50",
    fortyYard: "4.89",
    benchPress: "16",
    vertLeap: "34.0",
    broadJump: "116",
    shuttle: "4.32",
    threeCone: "7.35",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Andy Isabella",
    college: "Massachusetts",
    pos: "WR",
    height: "69.00",
    weight: "188",
    handSize: "8.38",
    armLength: "29.75",
    fortyYard: "4.31",
    benchPress: "15",
    vertLeap: "36.5",
    broadJump: "121",
    shuttle: "4.15",
    threeCone: "6.95",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Martez Ivey",
    college: "Florida",
    pos: "OG",
    height: "77.00",
    weight: "315",
    handSize: "10.38",
    armLength: "36.25",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Joe Jackson",
    college: "Miami (FL)",
    pos: "DE",
    height: "76.00",
    weight: "275",
    handSize: "10.00",
    armLength: "34.13",
    fortyYard: "22",
    benchPress: "27.0",
    vertLeap: "109",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mike Jackson",
    college: "Miami (FL)",
    pos: "CB",
    height: "73.00",
    weight: "210",
    handSize: "9.75",
    armLength: "32.50",
    fortyYard: "4.45",
    benchPress: "13",
    vertLeap: "40.5",
    broadJump: "130",
    shuttle: "4.12",
    threeCone: "7.12",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Tyree Jackson",
    college: "Buffalo",
    pos: "QB",
    height: "79.00",
    weight: "249",
    handSize: "10.25",
    armLength: "34.25",
    fortyYard: "4.59",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Josh Jacobs",
    college: "Alabama",
    pos: "RB",
    height: "70.00",
    weight: "220",
    handSize: "10.13",
    armLength: "31.63",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "CeCe Jefferson",
    college: "Florida",
    pos: "DE",
    height: "73.00",
    weight: "266",
    handSize: "9.63",
    armLength: "33.63",
    fortyYard: "5.02",
    benchPress: "17",
    vertLeap: "30.5",
    broadJump: "108",
    shuttle: "4.53",
    threeCone: "7.50",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jalen Jelks",
    college: "Oregon",
    pos: "EDG",
    height: "77.00",
    weight: "256",
    handSize: "9.63",
    armLength: "34.63",
    fortyYard: "4.92",
    benchPress: "19",
    vertLeap: "32.5",
    broadJump: "113",
    shuttle: "4.59",
    threeCone: "7.22",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Elgton Jenkins",
    college: "Mississippi State",
    pos: "OL",
    height: "76.00",
    weight: "310",
    handSize: "10.25",
    armLength: "34.00",
    fortyYard: "29",
    benchPress: "28.0",
    vertLeap: "109",
    broadJump: "4.62",
    shuttle: "7.77",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Gary Jennings",
    college: "West Virginia",
    pos: "WR",
    height: "73.00",
    weight: "214",
    handSize: "9.63",
    armLength: "32.50",
    fortyYard: "4.42",
    benchPress: "20",
    vertLeap: "37.0",
    broadJump: "127",
    shuttle: "4.15",
    threeCone: "7.32",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Anthony Johnson",
    college: "Buffalo",
    pos: "WR",
    height: "74.00",
    weight: "209",
    handSize: "9.38",
    armLength: "31.38",
    fortyYard: "18",
    benchPress: "32.5",
    vertLeap: "122",
    broadJump: "7.12",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Darryl Johnson",
    college: "North Carolina A&T",
    pos: "EDG",
    height: "78.00",
    weight: "253",
    handSize: "10.00",
    armLength: "33.88",
    fortyYard: "20",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Diontae Johnson",
    college: "Toledo",
    pos: "WR",
    height: "70.00",
    weight: "183",
    handSize: "9.00",
    armLength: "30.75",
    fortyYard: "4.53",
    benchPress: "15",
    vertLeap: "33.5",
    broadJump: "123",
    shuttle: "4.45",
    threeCone: "7.09",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Fred Johnson",
    college: "Florida",
    pos: "OL",
    height: "79.00",
    weight: "326",
    handSize: "10.63",
    armLength: "34.00",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Gary Johnson",
    college: "Texas",
    pos: "LB",
    height: "72.00",
    weight: "226",
    handSize: "10.25",
    armLength: "31.25",
    fortyYard: "4.43",
    benchPress: "16",
    vertLeap: "33.5",
    broadJump: "121",
    shuttle: "4.57",
    threeCone: "7.15",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Isaiah Johnson",
    college: "Houston",
    pos: "CB",
    height: "74.00",
    weight: "208",
    handSize: "8.75",
    armLength: "33.00",
    fortyYard: "4.40",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jaquan Johnson",
    college: "Miami (FL)",
    pos: "S",
    height: "70.00",
    weight: "191",
    handSize: "8.75",
    armLength: "29.63",
    fortyYard: "4.69",
    benchPress: "18",
    vertLeap: "33.0",
    broadJump: "121",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "KeeSean Johnson",
    college: "Frenso State (CA)",
    pos: "WR",
    height: "73.00",
    weight: "201",
    handSize: "9.50",
    armLength: "32.00",
    fortyYard: "4.60",
    benchPress: "14",
    vertLeap: "30.0",
    broadJump: "117",
    shuttle: "4.23",
    threeCone: "7.28",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Lonnie Johnson",
    college: "Kentucky",
    pos: "CB",
    height: "74.00",
    weight: "213",
    handSize: "9.13",
    armLength: "32.63",
    fortyYard: "4.52",
    benchPress: "15",
    vertLeap: "38.0",
    broadJump: "129",
    shuttle: "4.10",
    threeCone: "7.01",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Daniel Jones",
    college: "Duke",
    pos: "QB",
    height: "77.00",
    weight: "221",
    handSize: "9.75",
    armLength: "32.50",
    fortyYard: "4.81",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dre'Mont Jones",
    college: "Ohio State",
    pos: "DT",
    height: "75.00",
    weight: "281",
    handSize: "9.63",
    armLength: "33.75",
    fortyYard: "5.12",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jordan Jones",
    college: "Kentucky",
    pos: "LB",
    height: "74.00",
    weight: "234",
    handSize: "9.00",
    armLength: "31.75",
    fortyYard: "4.62",
    benchPress: "23",
    vertLeap: "32.5",
    broadJump: "123",
    shuttle: "4.37",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kendall Joseph",
    college: "Clemson",
    pos: "LB",
    height: "72.00",
    weight: "233",
    handSize: "9.75",
    armLength: "31.63",
    fortyYard: "25",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Vosean Joseph",
    college: "Florida",
    pos: "LB",
    height: "73.00",
    weight: "230",
    handSize: "9.63",
    armLength: "31.38",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kingsley Keke",
    college: "Texas A&M",
    pos: "DE",
    height: "75.00",
    weight: "288",
    handSize: "9.75",
    armLength: "34.50",
    fortyYard: "4.95",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dawson Knox",
    college: "Mississippi",
    pos: "TE",
    height: "76.00",
    weight: "254",
    handSize: "9.75",
    armLength: "33.50",
    fortyYard: "16",
    benchPress: "34.5",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Tre Lamar",
    college: "Clemson",
    pos: "LB",
    height: "75.00",
    weight: "253",
    handSize: "9.50",
    armLength: "32.25",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dexter Lawrence",
    college: "Clemson",
    pos: "DT",
    height: "76.00",
    weight: "342",
    handSize: "10.50",
    armLength: "34.75",
    fortyYard: "5.05",
    benchPress: "36",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Justin Layne",
    college: "Michigan State",
    pos: "CB",
    height: "74.00",
    weight: "192",
    handSize: "9.25",
    armLength: "33.00",
    fortyYard: "4.50",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jonathan Ledbetter",
    college: "Georgia",
    pos: "DE",
    height: "76.00",
    weight: "280",
    handSize: "9.88",
    armLength: "34.50",
    fortyYard: "5.14",
    benchPress: "22",
    vertLeap: "26.5",
    broadJump: "108",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Iman Lewis-Marshall",
    college: "Southern California",
    pos: "CB",
    height: "73.00",
    weight: "207",
    handSize: "9.50",
    armLength: "30.38",
    fortyYard: "4.53",
    benchPress: "16",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Chris Lindstrom",
    college: "Boston College",
    pos: "OG",
    height: "76.00",
    weight: "308",
    handSize: "9.50",
    armLength: "34.13",
    fortyYard: "4.91",
    benchPress: "25",
    vertLeap: "30.5",
    broadJump: "117",
    shuttle: "4.54",
    threeCone: "7.61",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Drew Lock",
    college: "Missouri",
    pos: "QB",
    height: "76.00",
    weight: "228",
    handSize: "9.00",
    armLength: "32.50",
    fortyYard: "4.69",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "David Long",
    college: "Michigan",
    pos: "CB",
    height: "71.00",
    weight: "196",
    handSize: "9.63",
    armLength: "30.88",
    fortyYard: "4.45",
    benchPress: "15",
    vertLeap: "39.5",
    broadJump: "120",
    shuttle: "3.97",
    threeCone: "6.45",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "David Long",
    college: "West Virginia",
    pos: "LB",
    height: "71.00",
    weight: "227",
    handSize: "10.00",
    armLength: "30.75",
    fortyYard: "4.45",
    benchPress: "15",
    vertLeap: "39.5",
    broadJump: "120",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jonathan Love",
    college: "Stanford",
    pos: "RB",
    height: "69.00",
    weight: "200",
    handSize: "9.13",
    armLength: "29.38",
    fortyYard: "18",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Julian Love",
    college: "Notre Dame",
    pos: "CB",
    height: "71.00",
    weight: "195",
    handSize: "9.00",
    armLength: "31.75",
    fortyYard: "4.54",
    benchPress: "14",
    vertLeap: "36.0",
    broadJump: "121",
    shuttle: "4.10",
    threeCone: "6.72",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Alize Mack",
    college: "Notre Dame",
    pos: "TE",
    height: "76.00",
    weight: "249",
    handSize: "9.38",
    armLength: "33.75",
    fortyYard: "4.70",
    benchPress: "22",
    vertLeap: "36.0",
    broadJump: "120",
    shuttle: "4.34",
    threeCone: "7.27",
    sixtyYardShuttle: "11.93"
  },
  {
    year: "2019",
    name: "Daylon Mack",
    college: "Texas A&M",
    pos: "DT",
    height: "73.00",
    weight: "336",
    handSize: "10.25",
    armLength: "31.25",
    fortyYard: "5.10",
    benchPress: "30",
    vertLeap: "27.0",
    broadJump: "102",
    shuttle: "4.95",
    threeCone: "8.02",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Alexander Mattison",
    college: "Boise State",
    pos: "RB",
    height: "71.00",
    weight: "221",
    handSize: "9.13",
    armLength: "31.00",
    fortyYard: "4.67",
    benchPress: "22",
    vertLeap: "35.0",
    broadJump: "127",
    shuttle: "4.29",
    threeCone: "7.13",
    sixtyYardShuttle: "11.69"
  },
  {
    year: "2019",
    name: "Erik McCoy",
    college: "Texas A&M",
    pos: "C",
    height: "76.00",
    weight: "303",
    handSize: "9.63",
    armLength: "33.00",
    fortyYard: "4.89",
    benchPress: "29",
    vertLeap: "31.0",
    broadJump: "107",
    shuttle: "4.62",
    threeCone: "8.28",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Connor McGovern",
    college: "Penn State",
    pos: "OL",
    height: "77.00",
    weight: "308",
    handSize: "9.88",
    armLength: "34.13",
    fortyYard: "28",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mark McLaurin",
    college: "Mississippi State",
    pos: "S",
    height: "73.00",
    weight: "212",
    handSize: "9.63",
    armLength: "31.63",
    fortyYard: "4.77",
    benchPress: "12",
    vertLeap: "36.0",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Trace McSorley",
    college: "Penn State",
    pos: "QB",
    height: "72.00",
    weight: "202",
    handSize: "9.13",
    armLength: "31.00",
    fortyYard: "4.57",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Christian Miller",
    college: "Alabama",
    pos: "EDG",
    height: "75.00",
    weight: "247",
    handSize: "9.75",
    armLength: "35.13",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jordan Miller",
    college: "Washington",
    pos: "CB",
    height: "73.00",
    weight: "186",
    handSize: "9.63",
    armLength: "32.88",
    fortyYard: "4.49",
    benchPress: "6",
    vertLeap: "37.0",
    broadJump: "125",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Shareef Miller",
    college: "Penn State",
    pos: "EDG",
    height: "76.00",
    weight: "254",
    handSize: "10.13",
    armLength: "33.63",
    fortyYard: "4.69",
    benchPress: "16",
    vertLeap: "29.5",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Gardner Minshew",
    college: "Washington State",
    pos: "QB",
    height: "73.00",
    weight: "225",
    handSize: "10.13",
    armLength: "31.75",
    fortyYard: "4.97",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "David Montgomery",
    college: "Iowa State",
    pos: "RB",
    height: "70.00",
    weight: "222",
    handSize: "9.25",
    armLength: "31.38",
    fortyYard: "4.63",
    benchPress: "15",
    vertLeap: "28.5",
    broadJump: "121",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jalin Moore",
    college: "Appalachian State (NC)",
    pos: "RB",
    height: "70.00",
    weight: "212",
    handSize: "9.25",
    armLength: "32.38",
    fortyYard: "27",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Foster Moreau",
    college: "Louisiana State",
    pos: "TE",
    height: "76.00",
    weight: "253",
    handSize: "9.63",
    armLength: "33.50",
    fortyYard: "4.66",
    benchPress: "22",
    vertLeap: "36.5",
    broadJump: "121",
    shuttle: "4.11",
    threeCone: "7.16",
    sixtyYardShuttle: "11.81"
  },
  {
    year: "2019",
    name: "Trayvon Mullen",
    college: "Clemson",
    pos: "CB",
    height: "73.00",
    weight: "199",
    handSize: "9.13",
    armLength: "31.00",
    fortyYard: "4.46",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Byron Murphy",
    college: "Washington",
    pos: "CB",
    height: "71.00",
    weight: "190",
    handSize: "8.88",
    armLength: "30.13",
    fortyYard: "4.55",
    benchPress: "14",
    vertLeap: "36.5",
    broadJump: "120",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kyler Murray",
    college: "Oklahoma",
    pos: "QB",
    height: "70.00",
    weight: "207",
    handSize: "9.50",
    armLength: "28.50",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Isaac Nauta",
    college: "Georgia",
    pos: "TE",
    height: "75.00",
    weight: "244",
    handSize: "9.38",
    armLength: "31.88",
    fortyYard: "4.91",
    benchPress: "19",
    vertLeap: "28.0",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Anthony Nelson",
    college: "Iowa",
    pos: "DE",
    height: "79.00",
    weight: "271",
    handSize: "9.88",
    armLength: "34.88",
    fortyYard: "4.82",
    benchPress: "18",
    vertLeap: "35.5",
    broadJump: "118",
    shuttle: "4.23",
    threeCone: "6.95",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Bobby Okereke",
    college: "Stanford",
    pos: "LB",
    height: "73.00",
    weight: "239",
    handSize: "10.13",
    armLength: "34.50",
    fortyYard: "4.58",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ed Oliver",
    college: "Houston",
    pos: "DT",
    height: "74.00",
    weight: "287",
    handSize: "9.25",
    armLength: "31.75",
    fortyYard: "32",
    benchPress: "36.0",
    vertLeap: "120",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Josh Oliver",
    college: "San Jose State",
    pos: "TE",
    height: "77.00",
    weight: "249",
    handSize: "10.75",
    armLength: "33.50",
    fortyYard: "4.63",
    benchPress: "22",
    vertLeap: "34.0",
    broadJump: "117",
    shuttle: "4.47",
    threeCone: "7.21",
    sixtyYardShuttle: "12.01"
  },
  {
    year: "2019",
    name: "Qadree Ollison",
    college: "Pittsburgh",
    pos: "RB",
    height: "73.00",
    weight: "228",
    handSize: "9.63",
    armLength: "31.50",
    fortyYard: "4.58",
    benchPress: "19",
    vertLeap: "29.5",
    broadJump: "114",
    shuttle: "4.31",
    threeCone: "7.53",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Charles Omenihu",
    college: "Texas",
    pos: "DE",
    height: "77.00",
    weight: "280",
    handSize: "9.38",
    armLength: "36.00",
    fortyYard: "4.92",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Iosua Opeta",
    college: "Weber State (UT)",
    pos: "OL",
    height: "76.00",
    weight: "301",
    handSize: "9.88",
    armLength: "33.25",
    fortyYard: "5.02",
    benchPress: "39",
    vertLeap: "33.0",
    broadJump: "112",
    shuttle: "4.94",
    threeCone: "8.06",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Amani Oruwariye",
    college: "Penn State",
    pos: "CB",
    height: "74.00",
    weight: "205",
    handSize: "9.00",
    armLength: "31.38",
    fortyYard: "4.47",
    benchPress: "17",
    vertLeap: "36.5",
    broadJump: "120",
    shuttle: "4.16",
    threeCone: "6.82",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Javon Patterson",
    college: "Mississippi",
    pos: "C",
    height: "75.00",
    weight: "307",
    handSize: "9.00",
    armLength: "32.50",
    fortyYard: "5.13",
    benchPress: "27",
    vertLeap: "27.5",
    broadJump: "98",
    shuttle: "4.78",
    threeCone: "7.72",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jamal Peters",
    college: "Mississippi State",
    pos: "CB",
    height: "74.00",
    weight: "218",
    handSize: "9.75",
    armLength: "32.38",
    fortyYard: "4.63",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jachai Polite",
    college: "Florida",
    pos: "EDG",
    height: "75.00",
    weight: "258",
    handSize: "9.75",
    armLength: "32.63",
    fortyYard: "4.84",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Tony Pollard",
    college: "Memphis",
    pos: "RB",
    height: "72.00",
    weight: "210",
    handSize: "9.50",
    armLength: "30.00",
    fortyYard: "4.52",
    benchPress: "13",
    vertLeap: "35.0",
    broadJump: "121",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ben Powers",
    college: "Oklahoma",
    pos: "OG",
    height: "76.00",
    weight: "307",
    handSize: "9.88",
    armLength: "33.75",
    fortyYard: "21",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Germaine Pratt",
    college: "North Carolina State",
    pos: "LB",
    height: "74.00",
    weight: "240",
    handSize: "9.13",
    armLength: "31.63",
    fortyYard: "4.57",
    benchPress: "24",
    vertLeap: "32.5",
    broadJump: "116",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Ryan Pulley",
    college: "Arkansas",
    pos: "CB",
    height: "71.00",
    weight: "209",
    handSize: "9.25",
    armLength: "32.75",
    fortyYard: "4.61",
    benchPress: "11",
    vertLeap: "31.0",
    broadJump: "111",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Taylor Rapp",
    college: "Washington",
    pos: "S",
    height: "72.00",
    weight: "208",
    handSize: "9.00",
    armLength: "30.75",
    fortyYard: "17",
    benchPress: "35.0",
    vertLeap: "115",
    broadJump: "3.99",
    shuttle: "6.82",
    threeCone: "11.33",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Wyatt Ray",
    college: "Boston College",
    pos: "EDG",
    height: "75.00",
    weight: "257",
    handSize: "9.38",
    armLength: "32.50",
    fortyYard: "4.83",
    benchPress: "25",
    vertLeap: "34.0",
    broadJump: "118",
    shuttle: "4.31",
    threeCone: "7.34",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dax Raymond",
    college: "Utah State",
    pos: "TE",
    height: "77.00",
    weight: "255",
    handSize: "10.25",
    armLength: "32.63",
    fortyYard: "4.73",
    benchPress: "15",
    vertLeap: "32.0",
    broadJump: "109",
    shuttle: "4.39",
    threeCone: "7.15",
    sixtyYardShuttle: "11.87"
  },
  {
    year: "2019",
    name: "Sheldrick Redwine",
    college: "Miami (FL)",
    pos: "S",
    height: "72.00",
    weight: "196",
    handSize: "9.38",
    armLength: "31.75",
    fortyYard: "4.44",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dontavius Russell",
    college: "Auburn",
    pos: "DT",
    height: "75.00",
    weight: "319",
    handSize: "9.50",
    armLength: "32.00",
    fortyYard: "5.15",
    benchPress: "24",
    vertLeap: "",
    broadJump: "4.77",
    shuttle: "7.81",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Brett Rypien",
    college: "Boise State",
    pos: "QB",
    height: "74.00",
    weight: "210",
    handSize: "9.00",
    armLength: "30.38",
    fortyYard: "4.91",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Drew Sample",
    college: "Washington",
    pos: "TE",
    height: "77.00",
    weight: "255",
    handSize: "9.63",
    armLength: "33.38",
    fortyYard: "4.71",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Miles Sanders",
    college: "Penn State",
    pos: "RB",
    height: "71.00",
    weight: "211",
    handSize: "9.25",
    armLength: "30.63",
    fortyYard: "4.49",
    benchPress: "20",
    vertLeap: "36.0",
    broadJump: "124",
    shuttle: "4.19",
    threeCone: "6.89",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Khalen Saunders",
    college: "Western Illinois",
    pos: "DT",
    height: "72.00",
    weight: "324",
    handSize: "9.13",
    armLength: "32.25",
    fortyYard: "5.01",
    benchPress: "27",
    vertLeap: "30.5",
    broadJump: "101",
    shuttle: "4.62",
    threeCone: "7.57",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Darnell Savage",
    college: "Maryland",
    pos: "S",
    height: "71.00",
    weight: "198",
    handSize: "9.13",
    armLength: "31.00",
    fortyYard: "4.36",
    benchPress: "11",
    vertLeap: "39.5",
    broadJump: "126",
    shuttle: "4.14",
    threeCone: "7.03",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jordan Scarlett",
    college: "Florida",
    pos: "RB",
    height: "71.00",
    weight: "208",
    handSize: "8.88",
    armLength: "30.38",
    fortyYard: "4.47",
    benchPress: "21",
    vertLeap: "30.0",
    broadJump: "116",
    shuttle: "4.63",
    threeCone: "7.37",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "LJ Scott",
    college: "Michigan State",
    pos: "RB",
    height: "72.00",
    weight: "227",
    handSize: "9.38",
    armLength: "32.13",
    fortyYard: "21",
    benchPress: "33.0",
    vertLeap: "120",
    broadJump: "4.34",
    shuttle: "7.27",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Austin Seibert",
    college: "Oklahoma",
    pos: "K",
    height: "69.00",
    weight: "213",
    handSize: "8.88",
    armLength: "30.38",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kendall Sheffield",
    college: "Ohio State",
    pos: "CB",
    height: "71.00",
    weight: "193",
    handSize: "9.25",
    armLength: "31.50",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kyle Shurmur",
    college: "Vanderbilt",
    pos: "QB",
    height: "76.00",
    weight: "230",
    handSize: "8.88",
    armLength: "32.75",
    fortyYard: "4.91",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Devin Singletary",
    college: "Florida Atlantic",
    pos: "RB",
    height: "67.00",
    weight: "203",
    handSize: "8.50",
    armLength: "28.88",
    fortyYard: "4.66",
    benchPress: "15",
    vertLeap: "35.0",
    broadJump: "117",
    shuttle: "4.40",
    threeCone: "7.32",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Chris Slayton",
    college: "Syracuse",
    pos: "DT",
    height: "76.00",
    weight: "307",
    handSize: "10.63",
    armLength: "33.50",
    fortyYard: "5.13",
    benchPress: "28",
    vertLeap: "29.0",
    broadJump: "101",
    shuttle: "4.73",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Cameron Smith",
    college: "Southern California",
    pos: "LB",
    height: "74.00",
    weight: "238",
    handSize: "10.38",
    armLength: "32.38",
    fortyYard: "4.69",
    benchPress: "15",
    vertLeap: "39.0",
    broadJump: "123",
    shuttle: "4.23",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Irv Smith",
    college: "Alabama",
    pos: "TE",
    height: "74.00",
    weight: "242",
    handSize: "9.50",
    armLength: "31.50",
    fortyYard: "4.63",
    benchPress: "19",
    vertLeap: "32.5",
    broadJump: "110",
    shuttle: "4.33",
    threeCone: "7.32",
    sixtyYardShuttle: "12.44"
  },
  {
    year: "2019",
    name: "Kaden Smith",
    college: "Stanford",
    pos: "TE",
    height: "77.00",
    weight: "255",
    handSize: "9.63",
    armLength: "32.25",
    fortyYard: "4.92",
    benchPress: "15",
    vertLeap: "32.0",
    broadJump: "108",
    shuttle: "4.47",
    threeCone: "7.08",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Sutton Smith",
    college: "Northern Illinois",
    pos: "EDG",
    height: "72.00",
    weight: "233",
    handSize: "9.00",
    armLength: "30.75",
    fortyYard: "4.69",
    benchPress: "25",
    vertLeap: "31.5",
    broadJump: "118",
    shuttle: "4.32",
    threeCone: "6.75",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Benny Snell",
    college: "Kentucky",
    pos: "RB",
    height: "70.00",
    weight: "224",
    handSize: "9.38",
    armLength: "31.00",
    fortyYard: "4.66",
    benchPress: "16",
    vertLeap: "29.5",
    broadJump: "119",
    shuttle: "4.33",
    threeCone: "7.07",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jace Sternberger",
    college: "Texas A&M",
    pos: "TE",
    height: "76.00",
    weight: "251",
    handSize: "9.75",
    armLength: "32.13",
    fortyYard: "4.75",
    benchPress: "17",
    vertLeap: "31.5",
    broadJump: "113",
    shuttle: "4.31",
    threeCone: "7.19",
    sixtyYardShuttle: "12.09"
  },
  {
    year: "2019",
    name: "Easton Stick",
    college: "North Dakota State",
    pos: "QB",
    height: "73.00",
    weight: "224",
    handSize: "9.25",
    armLength: "32.13",
    fortyYard: "4.62",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jarrett Stidham",
    college: "Auburn",
    pos: "QB",
    height: "74.00",
    weight: "218",
    handSize: "9.13",
    armLength: "32.00",
    fortyYard: "4.81",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Montez Sweat",
    college: "Mississippi State",
    pos: "EDG",
    height: "78.00",
    weight: "260",
    handSize: "10.50",
    armLength: "35.75",
    fortyYard: "4.41",
    benchPress: "21",
    vertLeap: "36.0",
    broadJump: "125",
    shuttle: "4.29",
    threeCone: "7.00",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Thomas Sweeney",
    college: "Boston College",
    pos: "TE",
    height: "76.00",
    weight: "251",
    handSize: "9.75",
    armLength: "32.75",
    fortyYard: "4.83",
    benchPress: "17",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jordan Ta'amu-Perifanos",
    college: "Mississippi",
    pos: "QB",
    height: "75.00",
    weight: "221",
    handSize: "9.88",
    armLength: "32.25",
    fortyYard: "4.77",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Trevon Tate",
    college: "Memphis",
    pos: "OG",
    height: "74.00",
    weight: "293",
    handSize: "9.63",
    armLength: "32.38",
    fortyYard: "22",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Marvell Tell",
    college: "Southern California",
    pos: "S",
    height: "74.00",
    weight: "198",
    handSize: "9.75",
    armLength: "33.13",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Deionte Thompson",
    college: "Alabama",
    pos: "S",
    height: "73.00",
    weight: "195",
    handSize: "9.88",
    armLength: "32.13",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Juan Thornhill",
    college: "Virginia",
    pos: "S",
    height: "72.00",
    weight: "205",
    handSize: "8.75",
    armLength: "31.13",
    fortyYard: "4.42",
    benchPress: "21",
    vertLeap: "44.0",
    broadJump: "141",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Clayton Thorson",
    college: "Northwestern",
    pos: "QB",
    height: "76.00",
    weight: "222",
    handSize: "9.75",
    armLength: "31.13",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Jerry Tillery",
    college: "Notre Dame",
    pos: "DT",
    height: "78.00",
    weight: "295",
    handSize: "10.63",
    armLength: "34.25",
    fortyYard: "4.93",
    benchPress: "23",
    vertLeap: "32.0",
    broadJump: "115",
    shuttle: "4.33",
    threeCone: "7.45",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Cole Tracy",
    college: "Louisiana State",
    pos: "K",
    height: "70.00",
    weight: "184",
    handSize: "9.13",
    armLength: "29.75",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "D'Andre Walker",
    college: "Georgia",
    pos: "EDG",
    height: "74.00",
    weight: "251",
    handSize: "9.88",
    armLength: "34.38",
    fortyYard: "",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Kahale Warring",
    college: "San Diego State",
    pos: "TE",
    height: "77.00",
    weight: "252",
    handSize: "9.75",
    armLength: "32.75",
    fortyYard: "4.67",
    benchPress: "19",
    vertLeap: "36.5",
    broadJump: "122",
    shuttle: "4.25",
    threeCone: "7.21",
    sixtyYardShuttle: "11.72"
  },
  {
    year: "2019",
    name: "Armon Watts",
    college: "Arkansas",
    pos: "DT",
    height: "77.00",
    weight: "300",
    handSize: "9.63",
    armLength: "33.38",
    fortyYard: "5.23",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mike Weber",
    college: "Ohio State",
    pos: "RB",
    height: "70.00",
    weight: "211",
    handSize: "9.38",
    armLength: "29.75",
    fortyYard: "4.47",
    benchPress: "22",
    vertLeap: "33.5",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Trevon Wesco",
    college: "West Virginia",
    pos: "TE",
    height: "75.00",
    weight: "267",
    handSize: "9.50",
    armLength: "34.75",
    fortyYard: "4.89",
    benchPress: "24",
    vertLeap: "31.0",
    broadJump: "117",
    shuttle: "4.38",
    threeCone: "7.18",
    sixtyYardShuttle: "12.32"
  },
  {
    year: "2019",
    name: "Darius West",
    college: "Kentucky",
    pos: "S",
    height: "71.00",
    weight: "208",
    handSize: "9.13",
    armLength: "31.38",
    fortyYard: "4.39",
    benchPress: "19",
    vertLeap: "33.5",
    broadJump: "113",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Dexter Williams",
    college: "Notre Dame",
    pos: "RB",
    height: "71.00",
    weight: "212",
    handSize: "9.63",
    armLength: "32.25",
    fortyYard: "4.57",
    benchPress: "17",
    vertLeap: "36.0",
    broadJump: "130",
    shuttle: "4.16",
    threeCone: "7.00",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "James Williams",
    college: "Washington State",
    pos: "RB",
    height: "69.00",
    weight: "197",
    handSize: "9.25",
    armLength: "30.38",
    fortyYard: "4.58",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Trayveon Williams",
    college: "Texas A&M",
    pos: "RB",
    height: "68.00",
    weight: "206",
    handSize: "9.25",
    armLength: "30.38",
    fortyYard: "4.51",
    benchPress: "19",
    vertLeap: "33.0",
    broadJump: "121",
    shuttle: "4.44",
    threeCone: "7.44",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Khari Willis",
    college: "Michigan State",
    pos: "S",
    height: "71.00",
    weight: "213",
    handSize: "9.50",
    armLength: "31.00",
    fortyYard: "4.52",
    benchPress: "22",
    vertLeap: "34.5",
    broadJump: "118",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Caleb Wilson",
    college: "UCLA",
    pos: "TE",
    height: "76.00",
    weight: "240",
    handSize: "9.75",
    armLength: "33.00",
    fortyYard: "4.56",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Donovan Wilson",
    college: "Texas A&M",
    pos: "S",
    height: "72.00",
    weight: "199",
    handSize: "9.75",
    armLength: "33.38",
    fortyYard: "18",
    benchPress: "36.0",
    vertLeap: "127",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Andrew Wingard",
    college: "Wyoming",
    pos: "S",
    height: "72.00",
    weight: "209",
    handSize: "8.63",
    armLength: "30.50",
    fortyYard: "4.56",
    benchPress: "9",
    vertLeap: "36.5",
    broadJump: "121",
    shuttle: "4.20",
    threeCone: "7.08",
    sixtyYardShuttle: "11.69"
  },
  {
    year: "2019",
    name: "Chase Winovich",
    college: "Michigan",
    pos: "EDG",
    height: "75.00",
    weight: "256",
    handSize: "10.00",
    armLength: "32.75",
    fortyYard: "4.59",
    benchPress: "18",
    vertLeap: "30.5",
    broadJump: "116",
    shuttle: "4.11",
    threeCone: "6.94",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Mitch Wishnowsky",
    college: "Utah",
    pos: "P",
    height: "74.00",
    weight: "218",
    handSize: "9.25",
    armLength: "31.25",
    fortyYard: "4.63",
    benchPress: "",
    vertLeap: "",
    broadJump: "",
    shuttle: "",
    threeCone: "",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Zedrick Woods",
    college: "Mississippi",
    pos: "S",
    height: "71.00",
    weight: "205",
    handSize: "9.13",
    armLength: "31.63",
    fortyYard: "4.29",
    benchPress: "19",
    vertLeap: "34.5",
    broadJump: "122",
    shuttle: "4.15",
    threeCone: "7.00",
    sixtyYardShuttle: ""
  },
  {
    year: "2019",
    name: "Evan Worthington",
    college: "Colorado",
    pos: "S",
    height: "74.00",
    weight: "212",
    handSize: "9.50",
    armLength: "32.75",
    fortyYard: "4.63",
    benchPress: "17",
    vertLeap: "33.5",
    broadJump: "121",
    shuttle: "4.37",
    threeCone: "7.07",
    sixtyYardShuttle: "11.88"
  },
  {
    year: "2019",
    name: "Oshane Ximines",
    college: "Old Dominion (VA)",
    pos: "EDG",
    height: "75.00",
    weight: "253",
    handSize: "9.88",
    armLength: "33.00",
    fortyYard: "4.78",
    benchPress: "24",
    vertLeap: "34.0",
    broadJump: "118",
    shuttle: "4.57",
    threeCone: "7.13",
    sixtyYardShuttle: ""
  }
];
